In [2]:
import pandas as pd
import numpy as np
import ga_ceed_6gen
import random

In [3]:
data_6_gen_df = pd.read_excel('ceed_data_6_gen.xlsx')
print(data_6_gen_df)

       a       b        c   alpha    beta  gamma  pmin  pmax
0  0.152  38.540   756.80  0.0042  0.3300  13.86    10   125
1  0.106  46.160   451.32  0.0042  0.3300  13.86    10   150
2  0.028  40.400  1050.00  0.0068 -0.5455  40.26    35   225
3  0.035  38.310  1243.53  0.0068 -0.5455  40.26    35   210
4  0.021  36.328  1658.57  0.0046 -0.5112  42.92   130   325
5  0.018  38.270  1356.66  0.0046 -0.5112  42.96   125   315


In [4]:
# get a,b,c column


In [5]:
# Random Candidate
cand = np.array([1,2, 1, 1, 1, 3])

In [6]:
ga_ceed_6gen.calc_hi(data_6_gen_df, cand,600)

0.022264267892110418

In [7]:
ga_ceed_6gen.calc_candidate_total_cost(cand, data_6_gen_df, 900)

6882.759960210513

In [8]:
popln = ga_ceed_6gen.initiate_population_random(data_6_gen_df, 8, 6, 800)
popln

array([[ 19., 148.,  50., 118., 298., 167.],
       [123., 143., 134.,  59., 203., 138.],
       [107.,  84., 128.,  96., 222., 163.],
       [119.,  66., 146.,  72., 212., 185.],
       [106.,  77., 119., 127., 174., 197.],
       [ 16.,  41.,  62., 190., 226., 265.],
       [ 86.,  31.,  71.,  74., 246., 292.],
       [ 54., 148.,  85.,  62., 196., 255.]])

In [9]:
popln_cost = ga_ceed_6gen.calculate_population_cost(popln, data_6_gen_df, 800)
popln_cost

array([[1.90000000e+01, 1.48000000e+02, 5.00000000e+01, 1.18000000e+02,
        2.98000000e+02, 1.67000000e+02, 4.31538919e+04],
       [1.23000000e+02, 1.43000000e+02, 1.34000000e+02, 5.90000000e+01,
        2.03000000e+02, 1.38000000e+02, 4.45006944e+04],
       [1.07000000e+02, 8.40000000e+01, 1.28000000e+02, 9.60000000e+01,
        2.22000000e+02, 1.63000000e+02, 4.24645856e+04],
       [1.19000000e+02, 6.60000000e+01, 1.46000000e+02, 7.20000000e+01,
        2.12000000e+02, 1.85000000e+02, 4.25526428e+04],
       [1.06000000e+02, 7.70000000e+01, 1.19000000e+02, 1.27000000e+02,
        1.74000000e+02, 1.97000000e+02, 4.23331215e+04],
       [1.60000000e+01, 4.10000000e+01, 6.20000000e+01, 1.90000000e+02,
        2.26000000e+02, 2.65000000e+02, 4.11010775e+04],
       [8.60000000e+01, 3.10000000e+01, 7.10000000e+01, 7.40000000e+01,
        2.46000000e+02, 2.92000000e+02, 4.14562031e+04],
       [5.40000000e+01, 1.48000000e+02, 8.50000000e+01, 6.20000000e+01,
        1.96000000e+02, 2

In [10]:
popln_cost_list = popln_cost.tolist()
print(popln_cost_list)

[[19.0, 148.0, 50.0, 118.0, 298.0, 167.0, 43153.8918728756], [123.0, 143.0, 134.0, 59.0, 203.0, 138.0, 44500.69443539469], [107.0, 84.0, 128.0, 96.0, 222.0, 163.0, 42464.585563850436], [119.0, 66.0, 146.0, 72.0, 212.0, 185.0, 42552.64276329919], [106.0, 77.0, 119.0, 127.0, 174.0, 197.0, 42333.12153334917], [16.0, 41.0, 62.0, 190.0, 226.0, 265.0, 41101.07748725523], [86.0, 31.0, 71.0, 74.0, 246.0, 292.0, 41456.203127299894], [54.0, 148.0, 85.0, 62.0, 196.0, 255.0, 43210.63838925149]]


In [11]:
def sortCost(val): 
    return val[-1]  

In [12]:
popln_cost_list.sort(key = sortCost)
popln_cost_list

[[16.0, 41.0, 62.0, 190.0, 226.0, 265.0, 41101.07748725523],
 [86.0, 31.0, 71.0, 74.0, 246.0, 292.0, 41456.203127299894],
 [106.0, 77.0, 119.0, 127.0, 174.0, 197.0, 42333.12153334917],
 [107.0, 84.0, 128.0, 96.0, 222.0, 163.0, 42464.585563850436],
 [119.0, 66.0, 146.0, 72.0, 212.0, 185.0, 42552.64276329919],
 [19.0, 148.0, 50.0, 118.0, 298.0, 167.0, 43153.8918728756],
 [54.0, 148.0, 85.0, 62.0, 196.0, 255.0, 43210.63838925149],
 [123.0, 143.0, 134.0, 59.0, 203.0, 138.0, 44500.69443539469]]

In [13]:
minimum = popln_cost_list[0]
print("Minimum Cost : ", popln_cost_list[0])

Minimum Cost :  [16.0, 41.0, 62.0, 190.0, 226.0, 265.0, 41101.07748725523]


In [14]:
# Select Parent Pool -- lowest parent costs
selected_parents = popln_cost_list[:4]
selected_parents

[[16.0, 41.0, 62.0, 190.0, 226.0, 265.0, 41101.07748725523],
 [86.0, 31.0, 71.0, 74.0, 246.0, 292.0, 41456.203127299894],
 [106.0, 77.0, 119.0, 127.0, 174.0, 197.0, 42333.12153334917],
 [107.0, 84.0, 128.0, 96.0, 222.0, 163.0, 42464.585563850436]]

In [15]:
selected_parents_arr = np.array(selected_parents)
selected_parents_arr

array([[1.60000000e+01, 4.10000000e+01, 6.20000000e+01, 1.90000000e+02,
        2.26000000e+02, 2.65000000e+02, 4.11010775e+04],
       [8.60000000e+01, 3.10000000e+01, 7.10000000e+01, 7.40000000e+01,
        2.46000000e+02, 2.92000000e+02, 4.14562031e+04],
       [1.06000000e+02, 7.70000000e+01, 1.19000000e+02, 1.27000000e+02,
        1.74000000e+02, 1.97000000e+02, 4.23331215e+04],
       [1.07000000e+02, 8.40000000e+01, 1.28000000e+02, 9.60000000e+01,
        2.22000000e+02, 1.63000000e+02, 4.24645856e+04]])

In [17]:
child = (selected_parents_arr[0] + selected_parents_arr[1])/2
child

array([5.10000000e+01, 3.60000000e+01, 6.65000000e+01, 1.32000000e+02,
       2.36000000e+02, 2.78500000e+02, 4.12786403e+04])

In [21]:
selected_parents_arr[:,:-1]

array([[ 16.,  41.,  62., 190., 226., 265.],
       [ 86.,  31.,  71.,  74., 246., 292.],
       [106.,  77., 119., 127., 174., 197.],
       [107.,  84., 128.,  96., 222., 163.]])