In [1]:
import pandas as pd
import numpy as np
import ga_ceed_6gen
import random

pdemand = 800
prob_mutation = 0.2

In [2]:
data_6_gen_df = pd.read_excel('ceed_data_6_gen.xlsx')
print(data_6_gen_df)

       a       b        c   alpha    beta  gamma  pmin  pmax
0  0.152  38.540   756.80  0.0042  0.3300  13.86    10   125
1  0.106  46.160   451.32  0.0042  0.3300  13.86    10   150
2  0.028  40.400  1050.00  0.0068 -0.5455  40.26    35   225
3  0.035  38.310  1243.53  0.0068 -0.5455  40.26    35   210
4  0.021  36.328  1658.57  0.0046 -0.5112  42.92   130   325
5  0.018  38.270  1356.66  0.0046 -0.5112  42.96   125   315


In [37]:
# get a,b,c column
a, b = data_6_gen_df.shape
a

6

In [4]:
# Random Candidate
cand = np.array([1,2, 1, 1, 1, 3])

In [5]:
ga_ceed_6gen.calc_hi(data_6_gen_df, cand,pdemand)

0.022264267892110418

In [6]:
ga_ceed_6gen.calc_candidate_total_cost(cand, data_6_gen_df, pdemand)

6882.685959517165

In [7]:
popln = ga_ceed_6gen.initiate_population_random(data_6_gen_df, 8, 6, pdemand)
popln

array([[ 35.,  62., 101., 167., 136., 299.],
       [ 64., 128., 185.,  82., 156., 185.],
       [ 46.,  36.,  81., 190., 195., 252.],
       [ 33.,  50., 221.,  89., 153., 254.],
       [ 93., 136., 113.,  77., 236., 145.],
       [ 49.,  81.,  80., 187., 246., 157.],
       [118.,  31., 134., 143., 201., 173.],
       [ 16.,  80.,  98., 170., 166., 270.]])

In [8]:
popln_cost = ga_ceed_6gen.calculate_population_cost(popln, data_6_gen_df, pdemand)
popln_cost

array([[3.50000000e+01, 6.20000000e+01, 1.01000000e+02, 1.67000000e+02,
        1.36000000e+02, 2.99000000e+02, 4.14563688e+04],
       [6.40000000e+01, 1.28000000e+02, 1.85000000e+02, 8.20000000e+01,
        1.56000000e+02, 1.85000000e+02, 4.29472210e+04],
       [4.60000000e+01, 3.60000000e+01, 8.10000000e+01, 1.90000000e+02,
        1.95000000e+02, 2.52000000e+02, 4.10923145e+04],
       [3.30000000e+01, 5.00000000e+01, 2.21000000e+02, 8.90000000e+01,
        1.53000000e+02, 2.54000000e+02, 4.14561106e+04],
       [9.30000000e+01, 1.36000000e+02, 1.13000000e+02, 7.70000000e+01,
        2.36000000e+02, 1.45000000e+02, 4.34174121e+04],
       [4.90000000e+01, 8.10000000e+01, 8.00000000e+01, 1.87000000e+02,
        2.46000000e+02, 1.57000000e+02, 4.16766700e+04],
       [1.18000000e+02, 3.10000000e+01, 1.34000000e+02, 1.43000000e+02,
        2.01000000e+02, 1.73000000e+02, 4.21462730e+04],
       [1.60000000e+01, 8.00000000e+01, 9.80000000e+01, 1.70000000e+02,
        1.66000000e+02, 2

In [9]:
popln_cost_list = popln_cost.tolist()
print(popln_cost_list)

[[35.0, 62.0, 101.0, 167.0, 136.0, 299.0, 41456.36882058303], [64.0, 128.0, 185.0, 82.0, 156.0, 185.0, 42947.2209588578], [46.0, 36.0, 81.0, 190.0, 195.0, 252.0, 41092.31450615117], [33.0, 50.0, 221.0, 89.0, 153.0, 254.0, 41456.110590339566], [93.0, 136.0, 113.0, 77.0, 236.0, 145.0, 43417.41209939995], [49.0, 81.0, 80.0, 187.0, 246.0, 157.0, 41676.66998423752], [118.0, 31.0, 134.0, 143.0, 201.0, 173.0, 42146.27297554369], [16.0, 80.0, 98.0, 170.0, 166.0, 270.0, 41563.71809577909]]


In [10]:
def sortCost(val): 
    return val[-1]  

In [11]:
popln_cost_list.sort(key = sortCost)
popln_cost_list

[[46.0, 36.0, 81.0, 190.0, 195.0, 252.0, 41092.31450615117],
 [33.0, 50.0, 221.0, 89.0, 153.0, 254.0, 41456.110590339566],
 [35.0, 62.0, 101.0, 167.0, 136.0, 299.0, 41456.36882058303],
 [16.0, 80.0, 98.0, 170.0, 166.0, 270.0, 41563.71809577909],
 [49.0, 81.0, 80.0, 187.0, 246.0, 157.0, 41676.66998423752],
 [118.0, 31.0, 134.0, 143.0, 201.0, 173.0, 42146.27297554369],
 [64.0, 128.0, 185.0, 82.0, 156.0, 185.0, 42947.2209588578],
 [93.0, 136.0, 113.0, 77.0, 236.0, 145.0, 43417.41209939995]]

In [12]:
minimum = popln_cost_list[0]
print("Minimum Cost : ", popln_cost_list[0])

Minimum Cost :  [46.0, 36.0, 81.0, 190.0, 195.0, 252.0, 41092.31450615117]


In [13]:
# Select Parent Pool -- lowest parent costs
selected_parents = popln_cost_list[:4]
selected_parents

[[46.0, 36.0, 81.0, 190.0, 195.0, 252.0, 41092.31450615117],
 [33.0, 50.0, 221.0, 89.0, 153.0, 254.0, 41456.110590339566],
 [35.0, 62.0, 101.0, 167.0, 136.0, 299.0, 41456.36882058303],
 [16.0, 80.0, 98.0, 170.0, 166.0, 270.0, 41563.71809577909]]

In [14]:
selected_parents_arr = np.array(selected_parents)
selected_parents_arr

array([[4.60000000e+01, 3.60000000e+01, 8.10000000e+01, 1.90000000e+02,
        1.95000000e+02, 2.52000000e+02, 4.10923145e+04],
       [3.30000000e+01, 5.00000000e+01, 2.21000000e+02, 8.90000000e+01,
        1.53000000e+02, 2.54000000e+02, 4.14561106e+04],
       [3.50000000e+01, 6.20000000e+01, 1.01000000e+02, 1.67000000e+02,
        1.36000000e+02, 2.99000000e+02, 4.14563688e+04],
       [1.60000000e+01, 8.00000000e+01, 9.80000000e+01, 1.70000000e+02,
        1.66000000e+02, 2.70000000e+02, 4.15637181e+04]])

In [15]:
parents = ga_ceed_6gen.parent_selection(popln_cost)
parents

array([[4.60000000e+01, 3.60000000e+01, 8.10000000e+01, 1.90000000e+02,
        1.95000000e+02, 2.52000000e+02, 4.10923145e+04],
       [3.30000000e+01, 5.00000000e+01, 2.21000000e+02, 8.90000000e+01,
        1.53000000e+02, 2.54000000e+02, 4.14561106e+04],
       [3.50000000e+01, 6.20000000e+01, 1.01000000e+02, 1.67000000e+02,
        1.36000000e+02, 2.99000000e+02, 4.14563688e+04],
       [1.60000000e+01, 8.00000000e+01, 9.80000000e+01, 1.70000000e+02,
        1.66000000e+02, 2.70000000e+02, 4.15637181e+04]])

In [16]:
cross_childs = ga_ceed_6gen.whole_linear_crossover(parents, data_6_gen_df, pdemand)
cross_childs

array([[3.02500000e+01, 6.65000000e+01, 1.00250000e+02, 1.67750000e+02,
        1.43500000e+02, 2.91750000e+02, 4.14599437e+04],
       [2.55000000e+01, 7.10000000e+01, 9.95000000e+01, 1.68500000e+02,
        1.51000000e+02, 2.84500000e+02, 4.14790269e+04],
       [3.95000000e+01, 4.30000000e+01, 1.51000000e+02, 1.39500000e+02,
        1.74000000e+02, 2.53000000e+02, 4.10256771e+04],
       [3.62500000e+01, 4.65000000e+01, 1.86000000e+02, 1.14250000e+02,
        1.63500000e+02, 2.53500000e+02, 4.11787599e+04]])

In [17]:
min(1,5)*5

5

In [24]:
mutate_childs = ga_ceed_6gen.mutation(cross_childs, data_6_gen_df, pdemand, prob_mutation)
mutate_childs

array([[3.02500000e+01, 4.53750000e+01, 1.00250000e+02, 1.88875000e+02,
        1.43500000e+02, 2.91750000e+02, 4.13077838e+04],
       [2.55000000e+01, 5.57500000e+01, 9.95000000e+01, 1.68500000e+02,
        1.51000000e+02, 2.99750000e+02, 4.13146358e+04],
       [3.95000000e+01, 4.30000000e+01, 1.20000000e+02, 1.39500000e+02,
        1.74000000e+02, 2.84000000e+02, 4.10245218e+04],
       [3.62500000e+01, 4.65000000e+01, 1.86000000e+02, 1.14250000e+02,
        1.63500000e+02, 2.53500000e+02, 4.11787599e+04]])

In [29]:
pop_no , gen_no = mutate_childs.shape
print(pop_no , gen_no)

4 7


In [32]:
child_parents = np.zeros([pop_no*2, gen_no])
child_parents

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [38]:
child_parents[:pop_no] = parents
child_parents[pop_no:] = mutate_childs
child_parents

array([[4.60000000e+01, 3.60000000e+01, 8.10000000e+01, 1.90000000e+02,
        1.95000000e+02, 2.52000000e+02, 4.10923145e+04],
       [3.30000000e+01, 5.00000000e+01, 2.21000000e+02, 8.90000000e+01,
        1.53000000e+02, 2.54000000e+02, 4.14561106e+04],
       [3.50000000e+01, 6.20000000e+01, 1.01000000e+02, 1.67000000e+02,
        1.36000000e+02, 2.99000000e+02, 4.14563688e+04],
       [1.60000000e+01, 8.00000000e+01, 9.80000000e+01, 1.70000000e+02,
        1.66000000e+02, 2.70000000e+02, 4.15637181e+04],
       [3.02500000e+01, 6.65000000e+01, 1.00250000e+02, 1.67750000e+02,
        1.43500000e+02, 2.91750000e+02, 4.14599437e+04],
       [2.55000000e+01, 7.10000000e+01, 9.95000000e+01, 1.68500000e+02,
        1.51000000e+02, 2.84500000e+02, 4.14790269e+04],
       [3.95000000e+01, 4.30000000e+01, 1.51000000e+02, 1.39500000e+02,
        1.74000000e+02, 2.53000000e+02, 4.10256771e+04],
       [3.62500000e+01, 4.65000000e+01, 1.86000000e+02, 1.14250000e+02,
        1.63500000e+02, 2

In [2]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
for i in range(0, 100, 10):
    print(i)


0
10
20
30
40
50
60
70
80
90
